### ISSUE TITLE
renderer won't load in blender 3.0

### ISSUE THREAD

**Issue by eballeste** [lunadigital/btoa#152]
hi hi! windows user here and I was trying to get this addon to load on blender 3.0. after unzipping the SDK files into a specific folder and installing the addon, i pointed the arnold root folder setting to the directory where i installed the SDK files but nothing happened. i got no errors but also was not getting the Arnold renderer as an option in the project render settings.

in my inexperience, i tried to point the folder to the `bin` folder where i started to get errors and could not for the life of me figure out how to reset the setting to point it to the root of the directory. now every time i try to disable/enable the addon i get the following:

```
Read prefs: C:\Users\cateresis\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend
No Arnold installation found. Settings from preferences: D:\Programs\Blender
Traceback (most recent call last):
  File "C:\Users\cateresis\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\btoa\addon_preferences.py", line 13, in refresh_addon
    bpy.ops.script.reload()
  File "D:\Programs\Blender\3.0\scripts\modules\bpy\ops.py", line 126, in __call__
    _BPyOpsSubModOp._view_layer_update(context)
  File "D:\Programs\Blender\3.0\scripts\modules\bpy\ops.py", line 88, in _view_layer_update
    view_layer = context.view_layer
AttributeError: '_RestrictContext' object has no attribute 'view_layer'
File "C:\Users\cateresis\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\btoa\addon_preferences.py", line 10, in refresh_addon
No custom OCIO config found, using default Filmic...
Exception in module register(): C:\Users\cateresis\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\btoa\__init__.py
Traceback (most recent call last):
  File "D:\Programs\Blender\3.0\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "C:\Users\cateresis\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\btoa\__init__.py", line 22, in register
    aienv.configure_plugins()
  File "C:\Users\cateresis\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\btoa\environ.py", line 63, in configure_plugins
    presets_root = bpy.utils.user_resource('SCRIPTS', "presets")
TypeError: user_resource() takes 1 positional argument but 2 were given
```

**Comment by eballeste** [comment]
just to make sure it wasn't an OS related issue, i installed blender 2.93.7, the addon, pointed it to the root of the SDK folder, and **was** able to get the Arnold renderer as an option.

**Comment by osiriswrecks** [comment]
Hi @eballeste eballeste! Unfortunately BtoA breaks in 3.0, this is a known issue. It's on my list of things to look at for the beta release, but once the fix makes it in you're welcome to download a dev build and play with it. I don't know when that will happen at the moment but keep an eye out and I'll be sure to also ping you here. Thanks for adding this to the tracker!
