### ISSUE TITLE
Arnold Won't Render Geometry with Ngons

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#17]
Blender 2.91.2
BtoA Dev Branch cb259ea
Arnold SDK 6.1.0
Windows 10 2004

Well, the bug is simple. If there are any ngons in the scene Arnold won't render.

Here is the error code:
```
Python: Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\btoa-feature-nodes\engine.py", line 96, in update
    node = btoa.generate_aipolymesh(ob, depsgraph)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\btoa-feature-nodes\btoa\bridge.py", line 62, in generate_aipolymesh
    mesh = bake_geometry(ob, depsgraph)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\btoa-feature-nodes\btoa\bridge.py", line 54, in bake_geometry
    mesh.calc_tangents()
RuntimeError: Error: Tangent space can only be computed for tris/quads, aborting
location: <unknown location>:-1
```

**Comment by osiriswrecks** [comment]
Good catch. Won't try to reproduce but I know how we can fix this.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky commit cd9ed7b above addresses this issue. When you get a chance can you confirm?
