### ISSUE TITLE
Disk lights return error on render

### ISSUE THREAD

**Issue by osiriswrecks** [lunadigital/btoa#188]
```
Traceback (most recent call last):
File "C:\Users\LUNADIGITAL\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\btoa\engine\__init__.py", line 157, in update                                                  
    self.session.export(self, depsgraph, prefs)
File "C:\Users\LUNADIGITAL\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\btoa\btoa\session.py", line 55, in export
    LightExporter(self).export(instance)
File "C:\Users\LUNADIGITAL\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\btoa\btoa\exporter\light_exporter.py", line 96, in export
    s = self.datablock.scale.x if self.datablock.scale.x > 0 else self.datablock.scale.y
```

**Comment by osiriswrecks** [comment]
Closing, this is no longer an issue.
