### ISSUE TITLE
Arnold Won't Render If Object is Edges or Vertices Only

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#28]
Blender 2.91.2
BtoA Master Branch e2820a1
Arnold SDK 6.1.0
Windows 10 2004

This is another "edge" case scenario. Arnold won't render if a scene has objects with only verts (**2**) or edges (**1**).
![image](https://user-images.githubusercontent.com/64398828/108194147-504fc380-7127-11eb-908a-84bb6ff2b26f.png)

Here is the error code:
```
Python: Traceback (most recent call last):
  File "C:\Users\Asiris\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\btoa-master\engine.py", line 97, in update
    node = btoa.generate_aipolymesh(ob, depsgraph)
  File "C:\Users\Asiris\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\btoa-master\btoa\bridge.py", line 68, in generate_aipolymesh
    mesh = bake_geometry(ob, depsgraph)
  File "C:\Users\Asiris\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\btoa-master\btoa\bridge.py", line 60, in bake_geometry
    mesh.calc_tangents()
RuntimeError: Error: Tangent space computation needs an UVMap, "(null)" not found, aborting

location: <unknown location>:-1
```

It's easy to reproduce but let me know if you need a scene file.

**Comment by AlexeyAdamitsky** [comment]
I believe it's fixed. Can't find issues with this anymore. Thanks!
