### ISSUE TITLE
Cant load the plugin Blender 2.93 (alpha)

### ISSUE THREAD

**Issue by GiorgioAdolfo** [lunadigital/btoa#77]
Heres the info ::

Traceback (most recent call last):
  File "/home/giorgio/blender-2.93.0-af940c68cbed-linux64/2.93/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/home/giorgio/.config/blender/2.93/scripts/addons/btoa/__init__.py", line 14, in register
    from . import props
  File "/home/giorgio/.config/blender/2.93/scripts/addons/btoa/props/__init__.py", line 2, in <module>
    from . import light
  File "/home/giorgio/.config/blender/2.93/scripts/addons/btoa/props/light.py", line 7, in <module>
    from .. import btoa
  File "/home/giorgio/.config/blender/2.93/scripts/addons/btoa/btoa/__init__.py", line 1, in <module>
    from .bridge import *
  File "/home/giorgio/.config/blender/2.93/scripts/addons/btoa/btoa/bridge.py", line 11, in <module>
    from arnold import *
ModuleNotFoundError: No module named 'arnold'

**Comment by GiorgioAdolfo** [comment]
Linux OS Centos 7

**Comment by AlexeyAdamitsky** [comment]
This is most likely connected to the fact that Blender is updated to Python 3.8.

I wouldn't recommend using alpha BtoA with alpha Blender builds.

**Comment by GiorgioAdolfo** [comment]
Thank you!!
Well, i ve tried again using the LTS 2.83 version of blender, and got this:
Traceback (most recent call last):
  File "/home/giorgio/Downloads/blender-2.83.10-linux64/2.83/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/home/giorgio/.config/blender/2.83/scripts/addons/btoa/__init__.py", line 14, in register
    from . import props
  File "/home/giorgio/.config/blender/2.83/scripts/addons/btoa/props/__init__.py", line 2, in <module>
    from . import light
  File "/home/giorgio/.config/blender/2.83/scripts/addons/btoa/props/light.py", line 7, in <module>
    from .. import btoa
  File "/home/giorgio/.config/blender/2.83/scripts/addons/btoa/btoa/__init__.py", line 1, in <module>
    from .bridge import *
  File "/home/giorgio/.config/blender/2.83/scripts/addons/btoa/btoa/bridge.py", line 11, in <module>
    from arnold import *
ModuleNotFoundError: No module named 'arnold'


Then when trying to enable the plugin inside blender a second time, got this:

Traceback (most recent call last):
  File "/home/giorgio/Downloads/blender-2.83.10-linux64/2.83/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/home/giorgio/.config/blender/2.83/scripts/addons/btoa/__init__.py", line 12, in register
    addon_preferences.register()
  File "/home/giorgio/.config/blender/2.83/scripts/addons/btoa/addon_preferences.py", line 124, in register
    bpy.utils.register_class(ArnoldAddonPreferences)
ValueError: register_class(...): already registered as a subclass 'ArnoldAddonPreferences'



Blender LTS Release 2.83.10  OS Centos 7

**Comment by osiriswrecks** [comment]
@GiorgioAdolfo Have you installed the Arnold SDK? We don't ship Arnold or the Arnold API with BtoA, it must be downloaded separately. 

If you have it installed and configured per the installation instructions and still have issues, try installing the latest from our dev branch. We have an alpha 0.2.0 release candidate ready for final testing before release later this week, you're welcome to download it now.

**Comment by osiriswrecks** [comment]
@GiorgioAdolfo Were you ever able to get this working? We've had a couple of alpha releases since you reported this issue so I wanted to check in with you before closing this issue out.

**Comment by AlexeyAdamitsky** [comment]
@osiriswrecks Can we run BtoA in 2.93? I haven't moved to 2.93 Beta yet because I couldn't run it. Most likely plugins compatibility issues. Didn't have the time to manually migrate to 2.93 yet since I need to check which plugin is causing issue. But BtoA should support latest Python version that Blender now requires, correct?

**Comment by osiriswrecks** [comment]
It depends on what "supporting the latest Python version" means. If the Arnold API doesn't work on Python 3.8, then that's out of our control and it will error out no matter what we do for now. If there are Python syntax changes that need to be made we can tackle those, but I rarely see breaking changes between minor versions like that. It will require more testing to figure out and 2.93 simply hasn't been on my radar up to this point (we're running the LTS at work and I'm testing on 2.92 at home I think).

**Comment by AlexeyAdamitsky** [comment]
I wasn't following this closely but I know that Blender bumped the version of Python they use(require?) to support future VFX pipelines. I think they made it so 2.93 LTS version was viable for the next 2 years they're planning to support it.

I'm not really aware of technical details but I know that some addons have to be updated for this change. I tried to automatically move my settings to 2.93 alpha for testing but it was crashing each time on launch. So I assume it was because of the addons. So I have to manually migrate to figure out which could cause the issues. I have a bunch installed.

Anyway, I'm not in a rush to move to 2.93 yet. Once it's final I'll definitely test if Arnold runs on it as expected. Right now don't have time to move everything manually.

**Comment by osiriswrecks** [comment]
This issue is now being tracked on #118 - closing as duplicate.
