### ISSUE TITLE
Cylinder Light Causing Render Error

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#89]
Blender 2.92
BtoA RC3 Branch 2a1b41d
Arnold SDK 6.1.0
Windows 10 2004

Arnold won't render with Cylinder Lights now.

```
Python: Traceback (most recent call last):
  File "C:\Users\Asiris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\btoa-alpha-rc3\engine.py", line 104, in update
    node = btoa_utils.create_light(object_instance)
  File "C:\Users\Asiris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\btoa-alpha-rc3\utils\btoa_utils.py", line 154, in create_light
    sync_light(node, object_instance)
  File "C:\Users\Asiris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\btoa-alpha-rc3\utils\btoa_utils.py", line 230, in sync_light
    top = matrix_utils.get_position_along_local_vector(data, d, 'Y')
  File "C:\Users\Asiris\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\btoa-alpha-rc3\utils\matrix_utils.py", line 11, in get_position_along_local_vector
    mv = Vector([0, distance, 0])
NameError: name 'Vector' is not defined

location: <unknown location>:-1
```

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky This should be fixed now. Please confirm when you get a chance!

**Comment by AlexeyAdamitsky** [comment]
No errors. Works as expected now. Thank you.
